require 'colorize'

require_relative 'board'
require_relative 'game'
require_relative 'graphics'
require_relative 'input'
require_relative 'move_type_selector'
require_relative 'move'
require_relative 'capture'
require_relative 'en_pass'

require_relative './pieces/piece'
require_relative './pieces/piece_constants'
require_relative './pieces/king'
require_relative './pieces/queen'
require_relative './pieces/bishop'
require_relative './pieces/knight'
require_relative './pieces/rook'
require_relative './pieces/pawn'

require_relative 'player'
require_relative 'turn'